name: "Update Docker Images"

on: [ push, pull_request ]

jobs:
  MoveTag:
    name: "Docker Image"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Build
        run: docker build -t tomasnorre/typo3teruploader:latest -f Docker/Dockerfile

      - name: Docker Push
        run: docker push tomasnorre/typo3teruploader:latest